emacs_src_dir: "{{ git_repos_dir }}/emacs"
chemacs_src_dir: "{{ anerenv_user_home }}/.emacs.d"
emacs_config_dir: "{{ config_dir }}/emacs"
lazymacs_dir: "{{ emacs_config_dir }}/lazymacs"
emacs_templates_dir: "{{ lazymacs_dir }}/templates"
notmuch_dir: "{{ git_repos_dir }}/notmuch"
org_dir: "{{ anerenv_user_home }}/org"
agenda_dir: "{{ org_dir }}/agenda"
journal_dir: "{{ org_dir }}/journal"
roam_dir: "{{ org_dir }}/roam"
projects_dir: "{{ anerenv_user_home }}/projects"
chess_dir: "{{ projects_dir }}/chess"
